import {
  addCard,
  analyze,
  askForRating,
  attachTag,
  deleteTag,
  detachTag,
  explain,
  getAudioPronunciation,
  getInternalSourceLanguage,
  getLanguagePairs,
  getCardsLimit,
  getSettings,
  isLoggedIn,
  removeCard,
  saveAskForRatingResponse,
  setSettings,
  updateCard,
  updateTag,
} from '@vocably/extension-messages';
import { merge } from 'lodash-es';
import { environmentLocal } from './environmentLocal';

export const environment = merge(environmentLocal, {
  production: true,
  updateCard: updateCard,
  analyze: analyze,
  explain: explain,
  addCard: addCard,
  attachTag: attachTag,
  detachTag: detachTag,
  deleteTag: deleteTag,
  updateTag: updateTag,
  removeCard: removeCard,
  getAudioPronunciation: getAudioPronunciation,
  getSettings: getSettings,
  setSettings: setSettings,
  isLoggedIn: isLoggedIn,
  getInternalSourceLanguage: getInternalSourceLanguage,
  getLanguagePairs: getLanguagePairs,
  askForRating: askForRating,
  saveAskForRatingResponse: saveAskForRatingResponse,
  getCardsLimit: getCardsLimit,
});
