version: 2.1
main_only: &main_only
  filters:
    branches:
      only: main

parameters:
  action:
    type: enum
    enum: ['none', 'kill dev', 'resurrect dev', 'kill prod', 'resurrect prod']
    default: 'none'

new_version_only: &new_version_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v\d+\.\d+\.\d+$/

commands:
  install_npm_dependencies:
    steps:
      - run:
          name: Set NPM cache folder
          command: npm set cache .npm
      - restore_cache:
          name: Restore NPM cache
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm ci --force
      - save_cache:
          name: Save NPM Cache
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - .npm

jobs:
  killApis:
    parameters:
      env_name:
        type: string
        default: 'DEV'
    docker:
      - image: cimg/node:22.18
    environment:
      ENV_NAME: << parameters.env_name >>
    steps:
      - checkout
      - run: bash ./scripts/install-build-dependencies.sh
      - run: bash ./scripts/declare-variables.sh
      - run: bash ./scripts/apis-kill.sh
  resurrectApis:
    parameters:
      env_name:
        type: string
        default: 'DEV'
    docker:
      - image: cimg/node:22.18
    environment:
      ENV_NAME: << parameters.env_name >>
    steps:
      - checkout
      - install_npm_dependencies
      - run: npx zx ./scripts/build-packages.mjs
      - run: bash ./scripts/install-build-dependencies.sh
      - run: bash ./scripts/declare-variables.sh
      - run: bash ./scripts/run-terraform.sh
  bumpNewVersion:
    working_directory: ~/repo
    docker:
      - image: cimg/node:22.18
    environment:
      ENV_NAME: DEV
    steps:
      - checkout
      - install_npm_dependencies
      - run: npx zx ./scripts/build-packages.mjs
      - run: npm run test -ws -- --runInBand --silent
      - run: bash ./scripts/install-build-dependencies.sh
      - run: bash ./scripts/declare-variables.sh
      - run: bash ./scripts/run-terraform.sh
      #      - run: npm run test -ws -- --runInBand --silent
      - run: npx semantic-release
      - run: npx zx ./scripts/build-extension.mjs

  prod:
    working_directory: ~/repo
    docker:
      - image: cimg/node:22.18
    environment:
      ENV_NAME: PROD
    steps:
      - checkout
      - install_npm_dependencies
      - run: npx zx ./scripts/build-packages.mjs
      - run: npm run test -ws -- --runInBand --silent
      - run: bash ./scripts/install-build-dependencies.sh
      - run: bash ./scripts/declare-variables.sh
      - run: bash ./scripts/run-terraform.sh
      - run: npx zx ./scripts/build-extension.mjs
workflows:
  version: 2
  killDev:
    when:
      equal: ['kill dev', << pipeline.parameters.action >>]
    jobs:
      - killApis:
          env_name: DEV
  resurrectDev:
    when:
      equal: ['resurrect dev', << pipeline.parameters.action >>]
    jobs:
      - resurrectApis:
          env_name: DEV

  bumpNewVersion:
    when:
      equal: ['webhook', << pipeline.trigger_source >>]
    max_auto_reruns: 3
    jobs:
      - bumpNewVersion:
          <<: *main_only
  deploy:
    jobs:
      - manual-testing:
          <<: *new_version_only
          type: approval
      - prod:
          <<: *new_version_only
          requires:
            - manual-testing
