/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AddCardPayload, AttachTagPayload, AudioPronunciationPayload, Card, CardItem, CardsLimit, DeleteTagPayload, DetachTagPayload, GoogleLanguage, GoogleTTSLanguage, LanguagePairs, RateInteractionPayload, RemoveCardPayload, Result, TagCandidate, TagItem, TranslationCard, TranslationCards, UpdateCardPayload, UpdateTagPayload } from "@vocably/model";
import { SearchValues } from "./components/search-form/types";
import { ComponentExplanationState } from "./components/translation/translation";
export namespace Components {
    interface VocablyAnimatedContentWrapper {
        "delay": number;
    }
    interface VocablyButton {
    }
    interface VocablyCardDefinitions {
        "card": TranslationCard;
        "isLightweight": boolean;
        "updateCard": (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyCardExamples {
        "example": string;
    }
    interface VocablyCardSource {
        "card": TranslationCard;
        "playAudioPronunciation": (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
    }
    interface VocablyCardTranslation {
        "card": TranslationCard;
        "disableEditing": boolean;
        "updateCard": (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyCloseButton {
    }
    interface VocablyFirstTranslationCongratulation {
        "card": TranslationCard;
    }
    interface VocablyHintSelector {
        "disabled": boolean;
        "hint": string;
        "optionGroups": Array<
    [groupLabel: string, options: Array<[value: string, label: string]>]
  >;
        "shrinkSmall": boolean;
        "value": string;
    }
    interface VocablyIconAdd {
    }
    interface VocablyIconAi {
    }
    interface VocablyIconArrowRight {
    }
    interface VocablyIconBookmarkCheck {
    }
    interface VocablyIconCheck {
    }
    interface VocablyIconClose {
    }
    interface VocablyIconEdit {
    }
    interface VocablyIconError {
    }
    interface VocablyIconMagnify {
    }
    interface VocablyIconPlayCircle {
    }
    interface VocablyIconPlus {
    }
    interface VocablyIconReload {
    }
    interface VocablyIconRemove {
    }
    interface VocablyIconSpin {
    }
    interface VocablyIconTag {
    }
    interface VocablyIconTagEdit {
    }
    interface VocablyIconVolumeMedium {
    }
    interface VocablyIconWindowClose {
    }
    interface VocablyInlineLoader {
        /**
          * Duration of the spinner animation in milliseconds. The default varies based on the spinner.
         */
        "duration"?: number;
        /**
          * If `true`, the spinner's animation will be paused.
         */
        "paused": boolean;
    }
    interface VocablyLanguage {
        "sourceLanguage": string;
        "targetLanguage": string;
        "waiting": boolean;
    }
    interface VocablyLogo {
    }
    interface VocablyMobileButton {
    }
    interface VocablyOverlay {
        "closeKeyCode": string[];
        "hide": () => Promise<void>;
    }
    interface VocablyPlaySound {
        "language": GoogleTTSLanguage;
        "play": () => Promise<void>;
        "playAudioPronunciation": (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "text": string;
    }
    interface VocablyPopup {
    }
    interface VocablyQrCode {
    }
    interface VocablyRate {
        "platform": { name: string; url: string };
    }
    interface VocablySearchForm {
        "autoFocus": boolean;
        "disabled": boolean;
        "existingSourceLanguages": GoogleLanguage[];
        "existingTargetLanguages": GoogleLanguage[];
        "hideHint": boolean;
        "languagePairs": LanguagePairs;
        "loading": boolean;
        "values": SearchValues;
    }
    interface VocablySignIn {
    }
    interface VocablySkeletonLoader {
    }
    interface VocablySpinner {
    }
    interface VocablySubscribe {
        "trial": boolean;
    }
    interface VocablyTagForm {
        "deleteTag"?: (tag: TagItem) => Promise<Result<unknown>>;
        "saveTag"?: (tag: TagCandidate) => Promise<Result<unknown>>;
        "tagItem": TagItem | null;
    }
    interface VocablyTagsMenu {
        "attachTag": (tag: TagItem) => Promise<Result<unknown>>;
        "deleteTag": (tag: TagItem) => Promise<Result<unknown>>;
        "detachTag": (tag: TagItem) => Promise<Result<unknown>>;
        "disabled": boolean;
        "existingItems": TagItem[];
        "saveTag": (tag: TagCandidate) => Promise<Result<unknown>>;
        "selectedItems": string[];
    }
    interface VocablyTranslation {
        "askForRating": boolean;
        "attachTag": (
    data: AttachTagPayload
  ) => Promise<Result<TranslationCards>>;
        "canCongratulate": boolean;
        "cardsLimit": CardsLimit;
        "deleteTag": (
    data: DeleteTagPayload
  ) => Promise<Result<TranslationCards>>;
        "detachTag": (
    data: DetachTagPayload
  ) => Promise<Result<TranslationCards>>;
        "disabled": boolean;
        "existingSourceLanguages": GoogleLanguage[];
        "existingTargetLanguages": GoogleLanguage[];
        "explanation": ComponentExplanationState;
        "explanationAnimationDelay": number;
        "extensionPlatform": {
    name: string;
    url: string;
    platform: 'chromeExtension' | 'safariExtension' | 'iosSafariExtension';
    paymentLink: string | false;
  };
        "hideChatGpt": boolean;
        "isLightweight": boolean;
        "isRetrying": boolean;
        "isUpdating": TranslationCard | null;
        "loading": boolean;
        "paymentLink": string;
        "phrase": string;
        "play": () => Promise<void>;
        "playAudioPronunciation": (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "result": Result<TranslationCards> | null;
        "showLanguages": boolean;
        "sourceLanguage": string;
        "targetLanguage": string;
        "updateCard": (
    payload: UpdateCardPayload
  ) => Promise<Result<TranslationCards>>;
        "updateTag": (
    data: UpdateTagPayload
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyTranslationCard {
        "addClick": () => void;
        "canAdd": boolean;
        "canCongratulate": boolean;
        "card": TranslationCard;
        "cardsLimit": CardsLimit;
        "detachTagHandler": (
    card: CardItem,
    tag: TagItem
  ) => () => Promise<any>;
        "disabled": boolean;
        "isLast": boolean;
        "isLightweight": boolean;
        "isUpdating": TranslationCard | null;
        "paymentLink": string;
        "playAudioPronunciation": (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "removeClick": () => void;
        "removing": { card: CardItem; tag: TagItem } | null;
        "showAddAttempt": boolean;
        "showCongratulation": boolean;
        "tagMenuClick": (target: HTMLElement) => void;
        "updateCard": (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
        "watchMePayingClick": () => void;
    }
}
export interface VocablyAnimatedContentWrapperCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyAnimatedContentWrapperElement;
}
export interface VocablyCloseButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyCloseButtonElement;
}
export interface VocablyHintSelectorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyHintSelectorElement;
}
export interface VocablyLanguageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyLanguageElement;
}
export interface VocablyPopupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyPopupElement;
}
export interface VocablyRateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyRateElement;
}
export interface VocablySearchFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablySearchFormElement;
}
export interface VocablySignInCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablySignInElement;
}
export interface VocablySubscribeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablySubscribeElement;
}
export interface VocablyTagFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyTagFormElement;
}
export interface VocablyTranslationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVocablyTranslationElement;
}
declare global {
    interface HTMLVocablyAnimatedContentWrapperElement extends Components.VocablyAnimatedContentWrapper, HTMLStencilElement {
    }
    var HTMLVocablyAnimatedContentWrapperElement: {
        prototype: HTMLVocablyAnimatedContentWrapperElement;
        new (): HTMLVocablyAnimatedContentWrapperElement;
    };
    interface HTMLVocablyButtonElement extends Components.VocablyButton, HTMLStencilElement {
    }
    var HTMLVocablyButtonElement: {
        prototype: HTMLVocablyButtonElement;
        new (): HTMLVocablyButtonElement;
    };
    interface HTMLVocablyCardDefinitionsElement extends Components.VocablyCardDefinitions, HTMLStencilElement {
    }
    var HTMLVocablyCardDefinitionsElement: {
        prototype: HTMLVocablyCardDefinitionsElement;
        new (): HTMLVocablyCardDefinitionsElement;
    };
    interface HTMLVocablyCardExamplesElement extends Components.VocablyCardExamples, HTMLStencilElement {
    }
    var HTMLVocablyCardExamplesElement: {
        prototype: HTMLVocablyCardExamplesElement;
        new (): HTMLVocablyCardExamplesElement;
    };
    interface HTMLVocablyCardSourceElement extends Components.VocablyCardSource, HTMLStencilElement {
    }
    var HTMLVocablyCardSourceElement: {
        prototype: HTMLVocablyCardSourceElement;
        new (): HTMLVocablyCardSourceElement;
    };
    interface HTMLVocablyCardTranslationElement extends Components.VocablyCardTranslation, HTMLStencilElement {
    }
    var HTMLVocablyCardTranslationElement: {
        prototype: HTMLVocablyCardTranslationElement;
        new (): HTMLVocablyCardTranslationElement;
    };
    interface HTMLVocablyCloseButtonElement extends Components.VocablyCloseButton, HTMLStencilElement {
    }
    var HTMLVocablyCloseButtonElement: {
        prototype: HTMLVocablyCloseButtonElement;
        new (): HTMLVocablyCloseButtonElement;
    };
    interface HTMLVocablyFirstTranslationCongratulationElement extends Components.VocablyFirstTranslationCongratulation, HTMLStencilElement {
    }
    var HTMLVocablyFirstTranslationCongratulationElement: {
        prototype: HTMLVocablyFirstTranslationCongratulationElement;
        new (): HTMLVocablyFirstTranslationCongratulationElement;
    };
    interface HTMLVocablyHintSelectorElement extends Components.VocablyHintSelector, HTMLStencilElement {
    }
    var HTMLVocablyHintSelectorElement: {
        prototype: HTMLVocablyHintSelectorElement;
        new (): HTMLVocablyHintSelectorElement;
    };
    interface HTMLVocablyIconAddElement extends Components.VocablyIconAdd, HTMLStencilElement {
    }
    var HTMLVocablyIconAddElement: {
        prototype: HTMLVocablyIconAddElement;
        new (): HTMLVocablyIconAddElement;
    };
    interface HTMLVocablyIconAiElement extends Components.VocablyIconAi, HTMLStencilElement {
    }
    var HTMLVocablyIconAiElement: {
        prototype: HTMLVocablyIconAiElement;
        new (): HTMLVocablyIconAiElement;
    };
    interface HTMLVocablyIconArrowRightElement extends Components.VocablyIconArrowRight, HTMLStencilElement {
    }
    var HTMLVocablyIconArrowRightElement: {
        prototype: HTMLVocablyIconArrowRightElement;
        new (): HTMLVocablyIconArrowRightElement;
    };
    interface HTMLVocablyIconBookmarkCheckElement extends Components.VocablyIconBookmarkCheck, HTMLStencilElement {
    }
    var HTMLVocablyIconBookmarkCheckElement: {
        prototype: HTMLVocablyIconBookmarkCheckElement;
        new (): HTMLVocablyIconBookmarkCheckElement;
    };
    interface HTMLVocablyIconCheckElement extends Components.VocablyIconCheck, HTMLStencilElement {
    }
    var HTMLVocablyIconCheckElement: {
        prototype: HTMLVocablyIconCheckElement;
        new (): HTMLVocablyIconCheckElement;
    };
    interface HTMLVocablyIconCloseElement extends Components.VocablyIconClose, HTMLStencilElement {
    }
    var HTMLVocablyIconCloseElement: {
        prototype: HTMLVocablyIconCloseElement;
        new (): HTMLVocablyIconCloseElement;
    };
    interface HTMLVocablyIconEditElement extends Components.VocablyIconEdit, HTMLStencilElement {
    }
    var HTMLVocablyIconEditElement: {
        prototype: HTMLVocablyIconEditElement;
        new (): HTMLVocablyIconEditElement;
    };
    interface HTMLVocablyIconErrorElement extends Components.VocablyIconError, HTMLStencilElement {
    }
    var HTMLVocablyIconErrorElement: {
        prototype: HTMLVocablyIconErrorElement;
        new (): HTMLVocablyIconErrorElement;
    };
    interface HTMLVocablyIconMagnifyElement extends Components.VocablyIconMagnify, HTMLStencilElement {
    }
    var HTMLVocablyIconMagnifyElement: {
        prototype: HTMLVocablyIconMagnifyElement;
        new (): HTMLVocablyIconMagnifyElement;
    };
    interface HTMLVocablyIconPlayCircleElement extends Components.VocablyIconPlayCircle, HTMLStencilElement {
    }
    var HTMLVocablyIconPlayCircleElement: {
        prototype: HTMLVocablyIconPlayCircleElement;
        new (): HTMLVocablyIconPlayCircleElement;
    };
    interface HTMLVocablyIconPlusElement extends Components.VocablyIconPlus, HTMLStencilElement {
    }
    var HTMLVocablyIconPlusElement: {
        prototype: HTMLVocablyIconPlusElement;
        new (): HTMLVocablyIconPlusElement;
    };
    interface HTMLVocablyIconReloadElement extends Components.VocablyIconReload, HTMLStencilElement {
    }
    var HTMLVocablyIconReloadElement: {
        prototype: HTMLVocablyIconReloadElement;
        new (): HTMLVocablyIconReloadElement;
    };
    interface HTMLVocablyIconRemoveElement extends Components.VocablyIconRemove, HTMLStencilElement {
    }
    var HTMLVocablyIconRemoveElement: {
        prototype: HTMLVocablyIconRemoveElement;
        new (): HTMLVocablyIconRemoveElement;
    };
    interface HTMLVocablyIconSpinElement extends Components.VocablyIconSpin, HTMLStencilElement {
    }
    var HTMLVocablyIconSpinElement: {
        prototype: HTMLVocablyIconSpinElement;
        new (): HTMLVocablyIconSpinElement;
    };
    interface HTMLVocablyIconTagElement extends Components.VocablyIconTag, HTMLStencilElement {
    }
    var HTMLVocablyIconTagElement: {
        prototype: HTMLVocablyIconTagElement;
        new (): HTMLVocablyIconTagElement;
    };
    interface HTMLVocablyIconTagEditElement extends Components.VocablyIconTagEdit, HTMLStencilElement {
    }
    var HTMLVocablyIconTagEditElement: {
        prototype: HTMLVocablyIconTagEditElement;
        new (): HTMLVocablyIconTagEditElement;
    };
    interface HTMLVocablyIconVolumeMediumElement extends Components.VocablyIconVolumeMedium, HTMLStencilElement {
    }
    var HTMLVocablyIconVolumeMediumElement: {
        prototype: HTMLVocablyIconVolumeMediumElement;
        new (): HTMLVocablyIconVolumeMediumElement;
    };
    interface HTMLVocablyIconWindowCloseElement extends Components.VocablyIconWindowClose, HTMLStencilElement {
    }
    var HTMLVocablyIconWindowCloseElement: {
        prototype: HTMLVocablyIconWindowCloseElement;
        new (): HTMLVocablyIconWindowCloseElement;
    };
    interface HTMLVocablyInlineLoaderElement extends Components.VocablyInlineLoader, HTMLStencilElement {
    }
    var HTMLVocablyInlineLoaderElement: {
        prototype: HTMLVocablyInlineLoaderElement;
        new (): HTMLVocablyInlineLoaderElement;
    };
    interface HTMLVocablyLanguageElement extends Components.VocablyLanguage, HTMLStencilElement {
    }
    var HTMLVocablyLanguageElement: {
        prototype: HTMLVocablyLanguageElement;
        new (): HTMLVocablyLanguageElement;
    };
    interface HTMLVocablyLogoElement extends Components.VocablyLogo, HTMLStencilElement {
    }
    var HTMLVocablyLogoElement: {
        prototype: HTMLVocablyLogoElement;
        new (): HTMLVocablyLogoElement;
    };
    interface HTMLVocablyMobileButtonElement extends Components.VocablyMobileButton, HTMLStencilElement {
    }
    var HTMLVocablyMobileButtonElement: {
        prototype: HTMLVocablyMobileButtonElement;
        new (): HTMLVocablyMobileButtonElement;
    };
    interface HTMLVocablyOverlayElement extends Components.VocablyOverlay, HTMLStencilElement {
    }
    var HTMLVocablyOverlayElement: {
        prototype: HTMLVocablyOverlayElement;
        new (): HTMLVocablyOverlayElement;
    };
    interface HTMLVocablyPlaySoundElement extends Components.VocablyPlaySound, HTMLStencilElement {
    }
    var HTMLVocablyPlaySoundElement: {
        prototype: HTMLVocablyPlaySoundElement;
        new (): HTMLVocablyPlaySoundElement;
    };
    interface HTMLVocablyPopupElement extends Components.VocablyPopup, HTMLStencilElement {
    }
    var HTMLVocablyPopupElement: {
        prototype: HTMLVocablyPopupElement;
        new (): HTMLVocablyPopupElement;
    };
    interface HTMLVocablyQrCodeElement extends Components.VocablyQrCode, HTMLStencilElement {
    }
    var HTMLVocablyQrCodeElement: {
        prototype: HTMLVocablyQrCodeElement;
        new (): HTMLVocablyQrCodeElement;
    };
    interface HTMLVocablyRateElement extends Components.VocablyRate, HTMLStencilElement {
    }
    var HTMLVocablyRateElement: {
        prototype: HTMLVocablyRateElement;
        new (): HTMLVocablyRateElement;
    };
    interface HTMLVocablySearchFormElement extends Components.VocablySearchForm, HTMLStencilElement {
    }
    var HTMLVocablySearchFormElement: {
        prototype: HTMLVocablySearchFormElement;
        new (): HTMLVocablySearchFormElement;
    };
    interface HTMLVocablySignInElement extends Components.VocablySignIn, HTMLStencilElement {
    }
    var HTMLVocablySignInElement: {
        prototype: HTMLVocablySignInElement;
        new (): HTMLVocablySignInElement;
    };
    interface HTMLVocablySkeletonLoaderElement extends Components.VocablySkeletonLoader, HTMLStencilElement {
    }
    var HTMLVocablySkeletonLoaderElement: {
        prototype: HTMLVocablySkeletonLoaderElement;
        new (): HTMLVocablySkeletonLoaderElement;
    };
    interface HTMLVocablySpinnerElement extends Components.VocablySpinner, HTMLStencilElement {
    }
    var HTMLVocablySpinnerElement: {
        prototype: HTMLVocablySpinnerElement;
        new (): HTMLVocablySpinnerElement;
    };
    interface HTMLVocablySubscribeElement extends Components.VocablySubscribe, HTMLStencilElement {
    }
    var HTMLVocablySubscribeElement: {
        prototype: HTMLVocablySubscribeElement;
        new (): HTMLVocablySubscribeElement;
    };
    interface HTMLVocablyTagFormElement extends Components.VocablyTagForm, HTMLStencilElement {
    }
    var HTMLVocablyTagFormElement: {
        prototype: HTMLVocablyTagFormElement;
        new (): HTMLVocablyTagFormElement;
    };
    interface HTMLVocablyTagsMenuElement extends Components.VocablyTagsMenu, HTMLStencilElement {
    }
    var HTMLVocablyTagsMenuElement: {
        prototype: HTMLVocablyTagsMenuElement;
        new (): HTMLVocablyTagsMenuElement;
    };
    interface HTMLVocablyTranslationElement extends Components.VocablyTranslation, HTMLStencilElement {
    }
    var HTMLVocablyTranslationElement: {
        prototype: HTMLVocablyTranslationElement;
        new (): HTMLVocablyTranslationElement;
    };
    interface HTMLVocablyTranslationCardElement extends Components.VocablyTranslationCard, HTMLStencilElement {
    }
    var HTMLVocablyTranslationCardElement: {
        prototype: HTMLVocablyTranslationCardElement;
        new (): HTMLVocablyTranslationCardElement;
    };
    interface HTMLElementTagNameMap {
        "vocably-animated-content-wrapper": HTMLVocablyAnimatedContentWrapperElement;
        "vocably-button": HTMLVocablyButtonElement;
        "vocably-card-definitions": HTMLVocablyCardDefinitionsElement;
        "vocably-card-examples": HTMLVocablyCardExamplesElement;
        "vocably-card-source": HTMLVocablyCardSourceElement;
        "vocably-card-translation": HTMLVocablyCardTranslationElement;
        "vocably-close-button": HTMLVocablyCloseButtonElement;
        "vocably-first-translation-congratulation": HTMLVocablyFirstTranslationCongratulationElement;
        "vocably-hint-selector": HTMLVocablyHintSelectorElement;
        "vocably-icon-add": HTMLVocablyIconAddElement;
        "vocably-icon-ai": HTMLVocablyIconAiElement;
        "vocably-icon-arrow-right": HTMLVocablyIconArrowRightElement;
        "vocably-icon-bookmark-check": HTMLVocablyIconBookmarkCheckElement;
        "vocably-icon-check": HTMLVocablyIconCheckElement;
        "vocably-icon-close": HTMLVocablyIconCloseElement;
        "vocably-icon-edit": HTMLVocablyIconEditElement;
        "vocably-icon-error": HTMLVocablyIconErrorElement;
        "vocably-icon-magnify": HTMLVocablyIconMagnifyElement;
        "vocably-icon-play-circle": HTMLVocablyIconPlayCircleElement;
        "vocably-icon-plus": HTMLVocablyIconPlusElement;
        "vocably-icon-reload": HTMLVocablyIconReloadElement;
        "vocably-icon-remove": HTMLVocablyIconRemoveElement;
        "vocably-icon-spin": HTMLVocablyIconSpinElement;
        "vocably-icon-tag": HTMLVocablyIconTagElement;
        "vocably-icon-tag-edit": HTMLVocablyIconTagEditElement;
        "vocably-icon-volume-medium": HTMLVocablyIconVolumeMediumElement;
        "vocably-icon-window-close": HTMLVocablyIconWindowCloseElement;
        "vocably-inline-loader": HTMLVocablyInlineLoaderElement;
        "vocably-language": HTMLVocablyLanguageElement;
        "vocably-logo": HTMLVocablyLogoElement;
        "vocably-mobile-button": HTMLVocablyMobileButtonElement;
        "vocably-overlay": HTMLVocablyOverlayElement;
        "vocably-play-sound": HTMLVocablyPlaySoundElement;
        "vocably-popup": HTMLVocablyPopupElement;
        "vocably-qr-code": HTMLVocablyQrCodeElement;
        "vocably-rate": HTMLVocablyRateElement;
        "vocably-search-form": HTMLVocablySearchFormElement;
        "vocably-sign-in": HTMLVocablySignInElement;
        "vocably-skeleton-loader": HTMLVocablySkeletonLoaderElement;
        "vocably-spinner": HTMLVocablySpinnerElement;
        "vocably-subscribe": HTMLVocablySubscribeElement;
        "vocably-tag-form": HTMLVocablyTagFormElement;
        "vocably-tags-menu": HTMLVocablyTagsMenuElement;
        "vocably-translation": HTMLVocablyTranslationElement;
        "vocably-translation-card": HTMLVocablyTranslationCardElement;
    }
}
declare namespace LocalJSX {
    interface VocablyAnimatedContentWrapper {
        "delay"?: number;
        "onClose"?: (event: VocablyAnimatedContentWrapperCustomEvent<void>) => void;
    }
    interface VocablyButton {
    }
    interface VocablyCardDefinitions {
        "card"?: TranslationCard;
        "isLightweight"?: boolean;
        "updateCard"?: (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyCardExamples {
        "example"?: string;
    }
    interface VocablyCardSource {
        "card"?: TranslationCard;
        "playAudioPronunciation"?: (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
    }
    interface VocablyCardTranslation {
        "card"?: TranslationCard;
        "disableEditing"?: boolean;
        "updateCard"?: (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyCloseButton {
        "onClose"?: (event: VocablyCloseButtonCustomEvent<void>) => void;
    }
    interface VocablyFirstTranslationCongratulation {
        "card"?: TranslationCard;
    }
    interface VocablyHintSelector {
        "disabled"?: boolean;
        "hint"?: string;
        "onChoose"?: (event: VocablyHintSelectorCustomEvent<string>) => void;
        "optionGroups"?: Array<
    [groupLabel: string, options: Array<[value: string, label: string]>]
  >;
        "shrinkSmall"?: boolean;
        "value"?: string;
    }
    interface VocablyIconAdd {
    }
    interface VocablyIconAi {
    }
    interface VocablyIconArrowRight {
    }
    interface VocablyIconBookmarkCheck {
    }
    interface VocablyIconCheck {
    }
    interface VocablyIconClose {
    }
    interface VocablyIconEdit {
    }
    interface VocablyIconError {
    }
    interface VocablyIconMagnify {
    }
    interface VocablyIconPlayCircle {
    }
    interface VocablyIconPlus {
    }
    interface VocablyIconReload {
    }
    interface VocablyIconRemove {
    }
    interface VocablyIconSpin {
    }
    interface VocablyIconTag {
    }
    interface VocablyIconTagEdit {
    }
    interface VocablyIconVolumeMedium {
    }
    interface VocablyIconWindowClose {
    }
    interface VocablyInlineLoader {
        /**
          * Duration of the spinner animation in milliseconds. The default varies based on the spinner.
         */
        "duration"?: number;
        /**
          * If `true`, the spinner's animation will be paused.
         */
        "paused"?: boolean;
    }
    interface VocablyLanguage {
        "onConfirm"?: (event: VocablyLanguageCustomEvent<{
    sourceLanguage: string;
    targetLanguage: string;
  }>) => void;
        "sourceLanguage"?: string;
        "targetLanguage"?: string;
        "waiting"?: boolean;
    }
    interface VocablyLogo {
    }
    interface VocablyMobileButton {
    }
    interface VocablyOverlay {
        "closeKeyCode"?: string[];
    }
    interface VocablyPlaySound {
        "language"?: GoogleTTSLanguage;
        "playAudioPronunciation"?: (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "text"?: string;
    }
    interface VocablyPopup {
        "onClose"?: (event: VocablyPopupCustomEvent<void>) => void;
    }
    interface VocablyQrCode {
    }
    interface VocablyRate {
        "onUserSelected"?: (event: VocablyRateCustomEvent<'review' | 'later' | 'never' | 'feedback'>) => void;
        "platform"?: { name: string; url: string };
    }
    interface VocablySearchForm {
        "autoFocus"?: boolean;
        "disabled"?: boolean;
        "existingSourceLanguages"?: GoogleLanguage[];
        "existingTargetLanguages"?: GoogleLanguage[];
        "hideHint"?: boolean;
        "languagePairs"?: LanguagePairs;
        "loading"?: boolean;
        "onFormSubmit"?: (event: VocablySearchFormCustomEvent<SearchValues>) => void;
        "onValuesChange"?: (event: VocablySearchFormCustomEvent<SearchValues>) => void;
        "values"?: SearchValues;
    }
    interface VocablySignIn {
        "onConfirm"?: (event: VocablySignInCustomEvent<any>) => void;
    }
    interface VocablySkeletonLoader {
    }
    interface VocablySpinner {
    }
    interface VocablySubscribe {
        "onConfirm"?: (event: VocablySubscribeCustomEvent<any>) => void;
        "trial"?: boolean;
    }
    interface VocablyTagForm {
        "deleteTag"?: (tag: TagItem) => Promise<Result<unknown>>;
        "onHide"?: (event: VocablyTagFormCustomEvent<void>) => void;
        "saveTag"?: (tag: TagCandidate) => Promise<Result<unknown>>;
        "tagItem"?: TagItem | null;
    }
    interface VocablyTagsMenu {
        "attachTag"?: (tag: TagItem) => Promise<Result<unknown>>;
        "deleteTag"?: (tag: TagItem) => Promise<Result<unknown>>;
        "detachTag"?: (tag: TagItem) => Promise<Result<unknown>>;
        "disabled"?: boolean;
        "existingItems"?: TagItem[];
        "saveTag"?: (tag: TagCandidate) => Promise<Result<unknown>>;
        "selectedItems"?: string[];
    }
    interface VocablyTranslation {
        "askForRating"?: boolean;
        "attachTag"?: (
    data: AttachTagPayload
  ) => Promise<Result<TranslationCards>>;
        "canCongratulate"?: boolean;
        "cardsLimit"?: CardsLimit;
        "deleteTag"?: (
    data: DeleteTagPayload
  ) => Promise<Result<TranslationCards>>;
        "detachTag"?: (
    data: DetachTagPayload
  ) => Promise<Result<TranslationCards>>;
        "disabled"?: boolean;
        "existingSourceLanguages"?: GoogleLanguage[];
        "existingTargetLanguages"?: GoogleLanguage[];
        "explanation"?: ComponentExplanationState;
        "explanationAnimationDelay"?: number;
        "extensionPlatform"?: {
    name: string;
    url: string;
    platform: 'chromeExtension' | 'safariExtension' | 'iosSafariExtension';
    paymentLink: string | false;
  };
        "hideChatGpt"?: boolean;
        "isLightweight"?: boolean;
        "isRetrying"?: boolean;
        "isUpdating"?: TranslationCard | null;
        "loading"?: boolean;
        "onAddCard"?: (event: VocablyTranslationCustomEvent<AddCardPayload>) => void;
        "onChangeSourceLanguage"?: (event: VocablyTranslationCustomEvent<string>) => void;
        "onChangeTargetLanguage"?: (event: VocablyTranslationCustomEvent<string>) => void;
        "onRatingInteraction"?: (event: VocablyTranslationCustomEvent<RateInteractionPayload>) => void;
        "onRemoveCard"?: (event: VocablyTranslationCustomEvent<RemoveCardPayload>) => void;
        "onRetry"?: (event: VocablyTranslationCustomEvent<void>) => void;
        "onWatchMePaying"?: (event: VocablyTranslationCustomEvent<void>) => void;
        "paymentLink"?: string;
        "phrase"?: string;
        "playAudioPronunciation"?: (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "result"?: Result<TranslationCards> | null;
        "showLanguages"?: boolean;
        "sourceLanguage"?: string;
        "targetLanguage"?: string;
        "updateCard"?: (
    payload: UpdateCardPayload
  ) => Promise<Result<TranslationCards>>;
        "updateTag"?: (
    data: UpdateTagPayload
  ) => Promise<Result<TranslationCards>>;
    }
    interface VocablyTranslationCard {
        "addClick"?: () => void;
        "canAdd"?: boolean;
        "canCongratulate"?: boolean;
        "card"?: TranslationCard;
        "cardsLimit"?: CardsLimit;
        "detachTagHandler"?: (
    card: CardItem,
    tag: TagItem
  ) => () => Promise<any>;
        "disabled"?: boolean;
        "isLast"?: boolean;
        "isLightweight"?: boolean;
        "isUpdating"?: TranslationCard | null;
        "paymentLink"?: string;
        "playAudioPronunciation"?: (
    payload: AudioPronunciationPayload
  ) => Promise<Result<true>>;
        "removeClick"?: () => void;
        "removing"?: { card: CardItem; tag: TagItem } | null;
        "showAddAttempt"?: boolean;
        "showCongratulation"?: boolean;
        "tagMenuClick"?: (target: HTMLElement) => void;
        "updateCard"?: (
    data: Partial<Card>
  ) => Promise<Result<TranslationCards>>;
        "watchMePayingClick"?: () => void;
    }
    interface IntrinsicElements {
        "vocably-animated-content-wrapper": VocablyAnimatedContentWrapper;
        "vocably-button": VocablyButton;
        "vocably-card-definitions": VocablyCardDefinitions;
        "vocably-card-examples": VocablyCardExamples;
        "vocably-card-source": VocablyCardSource;
        "vocably-card-translation": VocablyCardTranslation;
        "vocably-close-button": VocablyCloseButton;
        "vocably-first-translation-congratulation": VocablyFirstTranslationCongratulation;
        "vocably-hint-selector": VocablyHintSelector;
        "vocably-icon-add": VocablyIconAdd;
        "vocably-icon-ai": VocablyIconAi;
        "vocably-icon-arrow-right": VocablyIconArrowRight;
        "vocably-icon-bookmark-check": VocablyIconBookmarkCheck;
        "vocably-icon-check": VocablyIconCheck;
        "vocably-icon-close": VocablyIconClose;
        "vocably-icon-edit": VocablyIconEdit;
        "vocably-icon-error": VocablyIconError;
        "vocably-icon-magnify": VocablyIconMagnify;
        "vocably-icon-play-circle": VocablyIconPlayCircle;
        "vocably-icon-plus": VocablyIconPlus;
        "vocably-icon-reload": VocablyIconReload;
        "vocably-icon-remove": VocablyIconRemove;
        "vocably-icon-spin": VocablyIconSpin;
        "vocably-icon-tag": VocablyIconTag;
        "vocably-icon-tag-edit": VocablyIconTagEdit;
        "vocably-icon-volume-medium": VocablyIconVolumeMedium;
        "vocably-icon-window-close": VocablyIconWindowClose;
        "vocably-inline-loader": VocablyInlineLoader;
        "vocably-language": VocablyLanguage;
        "vocably-logo": VocablyLogo;
        "vocably-mobile-button": VocablyMobileButton;
        "vocably-overlay": VocablyOverlay;
        "vocably-play-sound": VocablyPlaySound;
        "vocably-popup": VocablyPopup;
        "vocably-qr-code": VocablyQrCode;
        "vocably-rate": VocablyRate;
        "vocably-search-form": VocablySearchForm;
        "vocably-sign-in": VocablySignIn;
        "vocably-skeleton-loader": VocablySkeletonLoader;
        "vocably-spinner": VocablySpinner;
        "vocably-subscribe": VocablySubscribe;
        "vocably-tag-form": VocablyTagForm;
        "vocably-tags-menu": VocablyTagsMenu;
        "vocably-translation": VocablyTranslation;
        "vocably-translation-card": VocablyTranslationCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vocably-animated-content-wrapper": LocalJSX.VocablyAnimatedContentWrapper & JSXBase.HTMLAttributes<HTMLVocablyAnimatedContentWrapperElement>;
            "vocably-button": LocalJSX.VocablyButton & JSXBase.HTMLAttributes<HTMLVocablyButtonElement>;
            "vocably-card-definitions": LocalJSX.VocablyCardDefinitions & JSXBase.HTMLAttributes<HTMLVocablyCardDefinitionsElement>;
            "vocably-card-examples": LocalJSX.VocablyCardExamples & JSXBase.HTMLAttributes<HTMLVocablyCardExamplesElement>;
            "vocably-card-source": LocalJSX.VocablyCardSource & JSXBase.HTMLAttributes<HTMLVocablyCardSourceElement>;
            "vocably-card-translation": LocalJSX.VocablyCardTranslation & JSXBase.HTMLAttributes<HTMLVocablyCardTranslationElement>;
            "vocably-close-button": LocalJSX.VocablyCloseButton & JSXBase.HTMLAttributes<HTMLVocablyCloseButtonElement>;
            "vocably-first-translation-congratulation": LocalJSX.VocablyFirstTranslationCongratulation & JSXBase.HTMLAttributes<HTMLVocablyFirstTranslationCongratulationElement>;
            "vocably-hint-selector": LocalJSX.VocablyHintSelector & JSXBase.HTMLAttributes<HTMLVocablyHintSelectorElement>;
            "vocably-icon-add": LocalJSX.VocablyIconAdd & JSXBase.HTMLAttributes<HTMLVocablyIconAddElement>;
            "vocably-icon-ai": LocalJSX.VocablyIconAi & JSXBase.HTMLAttributes<HTMLVocablyIconAiElement>;
            "vocably-icon-arrow-right": LocalJSX.VocablyIconArrowRight & JSXBase.HTMLAttributes<HTMLVocablyIconArrowRightElement>;
            "vocably-icon-bookmark-check": LocalJSX.VocablyIconBookmarkCheck & JSXBase.HTMLAttributes<HTMLVocablyIconBookmarkCheckElement>;
            "vocably-icon-check": LocalJSX.VocablyIconCheck & JSXBase.HTMLAttributes<HTMLVocablyIconCheckElement>;
            "vocably-icon-close": LocalJSX.VocablyIconClose & JSXBase.HTMLAttributes<HTMLVocablyIconCloseElement>;
            "vocably-icon-edit": LocalJSX.VocablyIconEdit & JSXBase.HTMLAttributes<HTMLVocablyIconEditElement>;
            "vocably-icon-error": LocalJSX.VocablyIconError & JSXBase.HTMLAttributes<HTMLVocablyIconErrorElement>;
            "vocably-icon-magnify": LocalJSX.VocablyIconMagnify & JSXBase.HTMLAttributes<HTMLVocablyIconMagnifyElement>;
            "vocably-icon-play-circle": LocalJSX.VocablyIconPlayCircle & JSXBase.HTMLAttributes<HTMLVocablyIconPlayCircleElement>;
            "vocably-icon-plus": LocalJSX.VocablyIconPlus & JSXBase.HTMLAttributes<HTMLVocablyIconPlusElement>;
            "vocably-icon-reload": LocalJSX.VocablyIconReload & JSXBase.HTMLAttributes<HTMLVocablyIconReloadElement>;
            "vocably-icon-remove": LocalJSX.VocablyIconRemove & JSXBase.HTMLAttributes<HTMLVocablyIconRemoveElement>;
            "vocably-icon-spin": LocalJSX.VocablyIconSpin & JSXBase.HTMLAttributes<HTMLVocablyIconSpinElement>;
            "vocably-icon-tag": LocalJSX.VocablyIconTag & JSXBase.HTMLAttributes<HTMLVocablyIconTagElement>;
            "vocably-icon-tag-edit": LocalJSX.VocablyIconTagEdit & JSXBase.HTMLAttributes<HTMLVocablyIconTagEditElement>;
            "vocably-icon-volume-medium": LocalJSX.VocablyIconVolumeMedium & JSXBase.HTMLAttributes<HTMLVocablyIconVolumeMediumElement>;
            "vocably-icon-window-close": LocalJSX.VocablyIconWindowClose & JSXBase.HTMLAttributes<HTMLVocablyIconWindowCloseElement>;
            "vocably-inline-loader": LocalJSX.VocablyInlineLoader & JSXBase.HTMLAttributes<HTMLVocablyInlineLoaderElement>;
            "vocably-language": LocalJSX.VocablyLanguage & JSXBase.HTMLAttributes<HTMLVocablyLanguageElement>;
            "vocably-logo": LocalJSX.VocablyLogo & JSXBase.HTMLAttributes<HTMLVocablyLogoElement>;
            "vocably-mobile-button": LocalJSX.VocablyMobileButton & JSXBase.HTMLAttributes<HTMLVocablyMobileButtonElement>;
            "vocably-overlay": LocalJSX.VocablyOverlay & JSXBase.HTMLAttributes<HTMLVocablyOverlayElement>;
            "vocably-play-sound": LocalJSX.VocablyPlaySound & JSXBase.HTMLAttributes<HTMLVocablyPlaySoundElement>;
            "vocably-popup": LocalJSX.VocablyPopup & JSXBase.HTMLAttributes<HTMLVocablyPopupElement>;
            "vocably-qr-code": LocalJSX.VocablyQrCode & JSXBase.HTMLAttributes<HTMLVocablyQrCodeElement>;
            "vocably-rate": LocalJSX.VocablyRate & JSXBase.HTMLAttributes<HTMLVocablyRateElement>;
            "vocably-search-form": LocalJSX.VocablySearchForm & JSXBase.HTMLAttributes<HTMLVocablySearchFormElement>;
            "vocably-sign-in": LocalJSX.VocablySignIn & JSXBase.HTMLAttributes<HTMLVocablySignInElement>;
            "vocably-skeleton-loader": LocalJSX.VocablySkeletonLoader & JSXBase.HTMLAttributes<HTMLVocablySkeletonLoaderElement>;
            "vocably-spinner": LocalJSX.VocablySpinner & JSXBase.HTMLAttributes<HTMLVocablySpinnerElement>;
            "vocably-subscribe": LocalJSX.VocablySubscribe & JSXBase.HTMLAttributes<HTMLVocablySubscribeElement>;
            "vocably-tag-form": LocalJSX.VocablyTagForm & JSXBase.HTMLAttributes<HTMLVocablyTagFormElement>;
            "vocably-tags-menu": LocalJSX.VocablyTagsMenu & JSXBase.HTMLAttributes<HTMLVocablyTagsMenuElement>;
            "vocably-translation": LocalJSX.VocablyTranslation & JSXBase.HTMLAttributes<HTMLVocablyTranslationElement>;
            "vocably-translation-card": LocalJSX.VocablyTranslationCard & JSXBase.HTMLAttributes<HTMLVocablyTranslationCardElement>;
        }
    }
}
