import {
  addCard,
  analyze,
  askForRating,
  attachTag,
  canPlayOffScreen,
  deleteTag,
  detachTag,
  explain,
  getAudioPronunciation,
  getInternalProxyLanguage,
  getInternalSourceLanguage,
  getLocationLanguage,
  getCardsLimit,
  getSettings,
  getUserEmail,
  isActive,
  isEligibleForTrial,
  isLoggedIn,
  isUserKnowsHowToAdd,
  listLanguages,
  listTargetLanguages,
  ping,
  playAudioPronunciation,
  removeCard,
  saveAskForRatingResponse,
  saveLocationLanguage,
  setInternalProxyLanguage,
  setInternalSourceLanguage,
  setUserKnowsHowToAdd,
  updateCard,
  updateTag,
  analyzeUnitsOfSpeech,
} from '@vocably/extension-messages';

export const api = {
  appBaseUrl: 'https://app.vocably.pro',
  isLoggedIn,
  getInternalProxyLanguage,
  setInternalProxyLanguage,
  getInternalSourceLanguage,
  setInternalSourceLanguage,
  analyze,
  addCard,
  removeCard,
  isActive,
  getCardsLimit,
  getUserEmail,
  ping,
  listLanguages,
  listTargetLanguages,
  isEligibleForTrial,
  isUserKnowsHowToAdd,
  setUserKnowsHowToAdd,
  getAudioPronunciation,
  playAudioPronunciation,
  canPlayOffScreen,
  askForRating,
  saveAskForRatingResponse,
  getLocationLanguage,
  saveLocationLanguage,
  getSettings,
  updateCard,
  attachTag,
  detachTag,
  updateTag,
  deleteTag,
  explain,
  analyzeUnitsOfSpeech,
};

export type ApiConfigOptions = Partial<typeof api>;

export const configureApi = (options: Partial<ApiConfigOptions>) => {
  Object.assign(api, options);
};
