root_domain                               = "dev.env.vocably.pro"
gcloud_project_id                         = "vocably-dev"
google_oauth2_client_id                   = "358366140631-qgk8e24k3ia92115kkl13arvj6vccdt8.apps.googleusercontent.com"
apple_sign_in_service_id                  = "pro.vocably.dev.auth"
apple_team_id                             = "789D8NRAM6"
extension_name                            = "Vocably - dev"
extension_content_script_excluded_matches = "\"http://localhost:8010/\", \"http://localhost:8020/\", \"http://localhost:8040/\""
extension_externally_connectable_matches  = "\"https://*.vocably.pro/*\", \"http://localhost/*\""
extension_extra_permissions               = ", \"scripting\""
extension_host_permissions                = "\"host_permissions\": [\"<all_urls>\"],"
extension_auto_reload                     = "true"
extension_key                             = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
chrome_extension_id                       = "mbpgmaflnlocikfiffhkjehhmnapkjgp"
umami_website_id                                  = "00593c34-002d-42f9-b128-445bdd1df6f6"
sentry_environment                        = "dev"
alarm_email                               = "dev@vocably.pro"
endtest_latest_env_suite                  = "547224"
paddle_client_side_token                  = "test_36e6911acf8912e58cde7765548"
paddle_monthly_premium_id                 = "pri_01jyzzammkt25f6mmf8tjsxr9p"
paddle_yearly_premium_id                  = "pri_01jz0ps01b1kcz9brm2877cbhg"
paddle_lifetime_premium_id                = "pri_01jz0pve2gry96kxkrk4n237qa"

# Public API route-specific throttle limits
public_api_analyze_throttle_rate_limit                   = 20
public_api_analyze_throttle_burst_limit                  = 20
public_api_audio_throttle_rate_limit                     = 20
public_api_audio_throttle_burst_limit                    = 20
public_api_feedback_throttle_rate_limit                  = 20
public_api_feedback_throttle_burst_limit                 = 20
public_api_generate_units_of_speech_throttle_rate_limit  = 20
public_api_generate_units_of_speech_throttle_burst_limit = 20
public_api_analyze_units_of_speech_throttle_rate_limit   = 20
public_api_analyze_units_of_speech_throttle_burst_limit  = 20
public_api_chat_with_card_throttle_rate_limit            = 20
public_api_chat_with_card_throttle_burst_limit           = 20
